### ISSUE TITLE
Final Presentations/Demo/Peer Review

### ISSUE THREAD

**Issue by sidneydurant** [CONNECT-iPhone/Application#15]
During the week of 11/28 - 12/02 & the following monday

Presentation time of team 44: Wednesday, 11/30- 3rd

**Comment by pmai6** [comment]
Peer Review:
  Monday, 11/28/16:
    - [ ] Team 49
    - [ ] Team 47
    - [ ] Team 20
Wednesday ,11/30/16:
    GROUP PRESENTATION, NO PEER REVIEW
Friday ,12/2/16:
    - [ ] Team 79
    - [ ] Team 15
    - [ ] Team 11
Monday, 12/5/16:
    - [ ] Team 4a
    - [ ] Team 13
